name: CI
on:
 workflow_dispatch
env:
  AZURE_WEBAPP_NAME: vycthor369-dev    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: dotnet build and publish
  run: |
    dotnet restore
    dotnet build --configuration Release
    dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 

  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev     
    needs: build
    steps:
        - name: 'Deploy to Azure WebApp'
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ env.vycthor369-dev }}
            publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
            package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp
          
  deploy-stage:
    runs-on: ubuntu-latest
    environment:
      name: stage      
    needs: deploy-dev
    steps:
        - name: Run a one-line script
          run: echo Deploy Prod
          
  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: 'nascimento.com' 
    needs: deploy-stage
    steps:
        - name: Run a one-line script
          run: echo Deploy Stage
          
          
     
          
