name: CI
on:
 workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Run a one-line script
          run: echo Hello, world!

  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'nascimento.com' 
    needs: build
    steps:
        - name: Run a one-line script
          run: echo Deploy Dev
          
  deploy-stage:
    runs-on: ubuntu-latest
    environment:
      name: stage
      url: 'nascimento.com' 
    needs: deploy-dev
    steps:
        - name: Run a one-line script
          run: echo Deploy Prod
          
  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: 'nascimento.com' 
    needs: deploy-stage
    steps:
        - name: Run a one-line script
          run: echo Deploy Stage
          
          
     
          
