name: CI
on:
 workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Run a one-line script
          run: echo Hello, world!

  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'nascimento.com' 
    needs: build
    steps:
        - name: 'Deploy to Azure WebApp'
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ env.vycthor369-dev }}
            publish-profile: ${{ secrets.vycthor369 }}
            package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          
  deploy-stage:
    runs-on: ubuntu-latest
    environment:
      name: stage
      url: 'nascimento.com' 
    needs: deploy-dev
    steps:
        - name: Run a one-line script
          run: echo Deploy Prod
          
  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: 'nascimento.com' 
    needs: deploy-stage
    steps:
        - name: Run a one-line script
          run: echo Deploy Stage
          
          
     
          
